postgres:
  defTimeout: 4 seconds
  jdbcDriver: org.postgresql.Driver
  namespaceSchema: public
  password: PLAYQ_SECRET_POSTGRES_PASSWORD
  synchronizer:
    acquireRetrySleep: 2 seconds
    ttl: 5 minutes
  url: url
  user: beetle

redis:
  authMode: AWS_IAM
  awsRegion: us-east-1
  awsReplicationGroupId: groupId
  awsUserId: beetle
  endpoint: redisendpoint
  integrationCheck: true
  password: PLAYQ_SECRET_REDIS_PASSWORD
  serverMode: CLUSTER
  user: redisuser
