# this is contract that defines how the service config map with be produced
# this is env independent
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

configMapGenerator:
  - name: beetle-config

generatorOptions:
  disableNameSuffixHash: true
