jwt:
  hmacSecret: "PUT_YOUR_HMAC_SECRET_HERE"
  publicKey: "PUBLIC_KEY"
  scheme: "Bearer"
  useHmac: false

redis:
  authMode: "AWS_IAM"
  awsRegion: "us-east-1"
  awsReplicationGroupId: "live-beetle"
  awsUserId: "live-beetle"
  endpoint: "rediss://clustercfg.live-beetle.7cdemb.use1.cache.amazonaws.com:6379"
  integrationCheck: true
  password: ""
  serverMode: "CLUSTER"
  user: ""
