apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

configMapGenerator:
  - name: beetle-config
    behavior: merge
    files:
      - dev-config.yaml=config.yaml
