apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: beetle-config
    files:
      - ../../base/config.yaml # base defaults
      - config.yaml # dev overrides
