apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: dev-beetle-config
    files:
      - global-config.yaml=../../global-config.yaml
      - service-config.yaml=service-config.yaml

options:
  disableNameSuffixHash: true
