aws:
  company: playq
  namespace: dev
  s3:
    buckets:
      - bucketName: attachments
        overrideName: ""
    connectionTimeout: 10 seconds
  tags:
    deployment: live
    environment: development
